[package]
name = "chaos_engine"
version = "0.1.0"
authors = ["Ólafur Þór Gunnarsson <olinord@gmail.com>"]
edition = "2024"

[dependencies]
vulkano = {version = "0.35.2", default-features = true}
vulkano-macros = "0.35.0"
winit = "0.30.12"
log = "0.4.11"
paste = "1.0"
spirv-reflect = "0.2.3"
quick-xml = "0.41.0"
cssparser = "0.37.0"
taffy = "0.13.0"
notify = "6"
notify-debouncer-mini = "0.4"
fontdue = "0.9"

chaos_communicator={ git="https://github.com/olinord/chaos_communicator", rev="40b9fc5"}